import { db } from "./db";
import { bcpPlanCatalog, bcpTestTemplates } from "@shared/schema";

// BC/DR Plan Catalog Templates
const bcpPlanCatalogData = [
  {
    code: "BCP-IT-DR-001",
    name: "IT Disaster Recovery Plan",
    description: "Comprehensive IT disaster recovery plan for restoring critical IT infrastructure, systems, and data following a major disruption.",
    category: "IT Disaster Recovery",
    planType: "disaster_recovery",
    applicableIndustries: ["All Industries", "Technology", "Financial Services", "Healthcare", "Manufacturing"],
    applicableScenarios: ["Data Center Failure", "Hardware Failure", "Software Corruption", "Ransomware Attack", "Natural Disaster"],
    sections: [
      { id: "overview", name: "Plan Overview", description: "Executive summary and scope" },
      { id: "roles", name: "Roles & Responsibilities", description: "DR team and contact information" },
      { id: "assessment", name: "Impact Assessment", description: "Critical systems and RTO/RPO requirements" },
      { id: "recovery", name: "Recovery Procedures", description: "Step-by-step recovery instructions" },
      { id: "communication", name: "Communication Plan", description: "Stakeholder notification procedures" },
      { id: "testing", name: "Testing Schedule", description: "Regular testing and validation requirements" },
    ],
    checklistItems: [
      "Identify critical IT systems and applications",
      "Define RTO and RPO for each system",
      "Establish backup and replication strategies",
      "Document recovery procedures",
      "Assign DR team roles",
      "Test recovery procedures quarterly",
    ],
    rtoGuidance: "Critical systems: 4-24 hours, Standard systems: 24-72 hours",
    rpoGuidance: "Critical data: 1-4 hours, Standard data: 24 hours",
    relatedFrameworks: ["ISO 22301", "NIST SP 800-34", "COBIT"],
    aiEnriched: true,
    aiTips: [
      { type: "tip", title: "Prioritize Critical Systems", content: "Start by identifying your tier-1 critical systems that directly impact revenue or customer service." },
      { type: "insight", title: "Cloud DR Benefits", content: "Consider cloud-based DR solutions for faster recovery times and reduced infrastructure costs." },
      { type: "prediction", title: "Common Gap", content: "Organizations often underestimate data synchronization requirements. Validate your RPO can be achieved with current backup frequency." },
    ],
  },
  {
    code: "BCP-PANDEMIC-001",
    name: "Pandemic Response Plan",
    description: "Business continuity plan for maintaining operations during pandemic events, including remote work enablement and health protocols.",
    category: "Crisis Management",
    planType: "pandemic",
    applicableIndustries: ["All Industries", "Healthcare", "Retail", "Manufacturing", "Education"],
    applicableScenarios: ["Global Pandemic", "Regional Health Crisis", "Widespread Illness", "Quarantine Requirements"],
    sections: [
      { id: "overview", name: "Plan Overview", description: "Pandemic response strategy and objectives" },
      { id: "health", name: "Health & Safety Protocols", description: "Employee health monitoring and safety measures" },
      { id: "remote", name: "Remote Work Procedures", description: "Work-from-home enablement and policies" },
      { id: "essential", name: "Essential Functions", description: "Critical operations and minimum staffing" },
      { id: "supply", name: "Supply Chain Continuity", description: "Alternative suppliers and inventory management" },
      { id: "communication", name: "Communication Strategy", description: "Employee and stakeholder updates" },
    ],
    checklistItems: [
      "Establish remote work infrastructure",
      "Define essential vs non-essential functions",
      "Create health screening protocols",
      "Identify alternative suppliers",
      "Develop employee communication plan",
      "Cross-train staff for critical functions",
    ],
    rtoGuidance: "Remote work capability: 24-48 hours, Essential operations: Continuous",
    rpoGuidance: "Critical business data must be accessible remotely with real-time sync",
    relatedFrameworks: ["ISO 22301", "OSHA Guidelines", "CDC Recommendations"],
    aiEnriched: true,
    aiTips: [
      { type: "tip", title: "VPN Capacity Planning", content: "Ensure your VPN infrastructure can handle 100% remote workforce simultaneously." },
      { type: "insight", title: "Succession Planning", content: "Identify backup personnel for all critical roles in case key staff become unavailable." },
      { type: "prediction", title: "Supply Chain Risk", content: "Diversify suppliers across different geographic regions to reduce single-point-of-failure risks." },
    ],
  },
  {
    code: "BCP-CYBER-001",
    name: "Cyber Incident Response Plan",
    description: "Specialized plan for responding to and recovering from cybersecurity incidents including ransomware, data breaches, and system compromises.",
    category: "Cyber Incident",
    planType: "cyber",
    applicableIndustries: ["All Industries", "Financial Services", "Healthcare", "Technology", "Government"],
    applicableScenarios: ["Ransomware Attack", "Data Breach", "DDoS Attack", "Insider Threat", "Advanced Persistent Threat", "Phishing Compromise"],
    sections: [
      { id: "preparation", name: "Preparation", description: "Preventive measures and readiness" },
      { id: "detection", name: "Detection & Analysis", description: "Incident identification and assessment" },
      { id: "containment", name: "Containment Strategy", description: "Limiting incident impact" },
      { id: "eradication", name: "Eradication", description: "Removing threat actors and malware" },
      { id: "recovery", name: "Recovery", description: "System restoration and validation" },
      { id: "lessons", name: "Post-Incident Review", description: "Lessons learned and improvements" },
    ],
    checklistItems: [
      "Establish incident response team",
      "Define incident classification criteria",
      "Create isolation procedures",
      "Document forensic preservation steps",
      "Prepare regulatory notification templates",
      "Maintain offline backup copies",
    ],
    rtoGuidance: "Containment: 1-4 hours, Full recovery: 24-72 hours depending on scope",
    rpoGuidance: "Critical: 0-1 hour with immutable backups, Standard: 4-24 hours",
    relatedFrameworks: ["NIST CSF", "ISO 27001", "NIST SP 800-61", "MITRE ATT&CK"],
    aiEnriched: true,
    aiTips: [
      { type: "tip", title: "Isolate First", content: "When ransomware is detected, immediately isolate affected systems to prevent lateral movement." },
      { type: "insight", title: "Backup Testing", content: "Regularly test backup restoration - ransomware recovery success depends on verified, clean backups." },
      { type: "prediction", title: "Double Extortion Trend", content: "Modern ransomware often includes data exfiltration. Plan for potential data disclosure even with recovery." },
    ],
  },
  {
    code: "BCP-NATURAL-001",
    name: "Natural Disaster Recovery Plan",
    description: "Business continuity plan for responding to natural disasters including earthquakes, floods, hurricanes, and severe weather events.",
    category: "Natural Disaster",
    planType: "disaster_recovery",
    applicableIndustries: ["All Industries", "Manufacturing", "Retail", "Logistics", "Healthcare"],
    applicableScenarios: ["Earthquake", "Flood", "Hurricane/Typhoon", "Tornado", "Wildfire", "Severe Weather"],
    sections: [
      { id: "assessment", name: "Risk Assessment", description: "Geographic and seasonal risk analysis" },
      { id: "prevention", name: "Prevention & Mitigation", description: "Physical safeguards and preparations" },
      { id: "evacuation", name: "Evacuation Procedures", description: "Employee safety and facility evacuation" },
      { id: "alternate", name: "Alternate Site Operations", description: "Backup location and remote work" },
      { id: "recovery", name: "Facility Recovery", description: "Building restoration and equipment replacement" },
      { id: "insurance", name: "Insurance & Claims", description: "Coverage verification and claims process" },
    ],
    checklistItems: [
      "Assess facility geographic risks",
      "Implement physical safeguards",
      "Establish alternate work locations",
      "Create employee emergency contacts",
      "Verify insurance coverage annually",
      "Stockpile emergency supplies",
    ],
    rtoGuidance: "Critical operations: 24-48 hours at alternate site, Full facility: 2-4 weeks",
    rpoGuidance: "All critical data must be replicated off-site with maximum 4-hour lag",
    relatedFrameworks: ["ISO 22301", "FEMA Guidelines", "OSHA"],
    aiEnriched: true,
    aiTips: [
      { type: "tip", title: "Geographic Redundancy", content: "Maintain backup sites at least 200 miles from primary location to avoid regional disasters affecting both." },
      { type: "insight", title: "Early Warning Integration", content: "Subscribe to NOAA and local emergency alert systems for advance warning of severe weather." },
      { type: "prediction", title: "Climate Trends", content: "Consider climate change impacts on historical risk assessments - events are becoming more frequent and severe." },
    ],
  },
  {
    code: "BCP-CRISIS-001",
    name: "Crisis Management Plan",
    description: "Comprehensive crisis management plan for coordinating organizational response to any significant business disruption or emergency.",
    category: "Crisis Management",
    planType: "crisis",
    applicableIndustries: ["All Industries", "Public Sector", "Healthcare", "Financial Services"],
    applicableScenarios: ["Any Major Disruption", "Reputational Crisis", "Leadership Crisis", "Regulatory Crisis", "Financial Crisis"],
    sections: [
      { id: "governance", name: "Crisis Governance", description: "Command structure and decision authority" },
      { id: "assessment", name: "Situation Assessment", description: "Rapid impact evaluation framework" },
      { id: "response", name: "Response Activation", description: "Crisis team mobilization procedures" },
      { id: "communication", name: "Crisis Communication", description: "Internal and external messaging" },
      { id: "stakeholder", name: "Stakeholder Management", description: "Customer, regulator, and media relations" },
      { id: "recovery", name: "Recovery & Normalization", description: "Return to normal operations" },
    ],
    checklistItems: [
      "Define crisis classification levels",
      "Establish crisis management team",
      "Create communication templates",
      "Prepare media response guidelines",
      "Document escalation procedures",
      "Conduct regular crisis drills",
    ],
    rtoGuidance: "Crisis team activation: 1 hour, Initial response: 4 hours, Full mobilization: 24 hours",
    rpoGuidance: "Crisis documentation and decisions must be captured in real-time",
    relatedFrameworks: ["ISO 22301", "ISO 31000", "COSO ERM"],
    aiEnriched: true,
    aiTips: [
      { type: "tip", title: "Single Spokesperson", content: "Designate one trained spokesperson for all external communications to ensure message consistency." },
      { type: "insight", title: "Social Media Monitoring", content: "Monitor social media in real-time during crises - public perception can escalate situations rapidly." },
      { type: "prediction", title: "Cascade Effects", content: "Initial crises often trigger secondary issues. Plan for cascading impacts across operations, reputation, and finances." },
    ],
  },
  {
    code: "BCP-SUPPLY-001",
    name: "Supply Chain Disruption Plan",
    description: "Plan for maintaining supply chain continuity during disruptions including supplier failures, logistics issues, and material shortages.",
    category: "Business Continuity",
    planType: "continuity",
    applicableIndustries: ["Manufacturing", "Retail", "Logistics", "Healthcare", "Automotive"],
    applicableScenarios: ["Supplier Failure", "Logistics Disruption", "Material Shortage", "Port Closure", "Trade Restrictions"],
    sections: [
      { id: "mapping", name: "Supply Chain Mapping", description: "Critical supplier and dependency identification" },
      { id: "risk", name: "Risk Assessment", description: "Supplier risk evaluation and monitoring" },
      { id: "alternatives", name: "Alternative Suppliers", description: "Backup supplier identification and qualification" },
      { id: "inventory", name: "Strategic Inventory", description: "Safety stock and buffer management" },
      { id: "logistics", name: "Alternative Logistics", description: "Backup transportation and routing" },
      { id: "communication", name: "Supplier Communication", description: "Early warning and coordination protocols" },
    ],
    checklistItems: [
      "Map tier 1-3 suppliers",
      "Identify single-source dependencies",
      "Qualify backup suppliers",
      "Establish safety stock levels",
      "Create supplier communication protocols",
      "Monitor supplier financial health",
    ],
    rtoGuidance: "Alternative supplier activation: 48-72 hours, Full supply restoration: 1-4 weeks",
    rpoGuidance: "Maintain minimum 2-week buffer stock for critical materials",
    relatedFrameworks: ["ISO 22301", "ISO 28000", "SCRM Practices"],
    aiEnriched: true,
    aiTips: [
      { type: "tip", title: "Dual Sourcing", content: "Maintain at least two qualified suppliers for all critical components to reduce single-source risk." },
      { type: "insight", title: "Visibility Gap", content: "Most organizations lack visibility beyond tier-1 suppliers. Map critical tier-2 and tier-3 dependencies." },
      { type: "prediction", title: "Geopolitical Awareness", content: "Monitor geopolitical developments in regions where key suppliers operate for early warning of potential disruptions." },
    ],
  },
  {
    code: "BCP-FACILITY-001",
    name: "Facility Loss Recovery Plan",
    description: "Plan for continuing operations following loss of access to primary business facilities due to fire, structural damage, or other events.",
    category: "Business Continuity",
    planType: "continuity",
    applicableIndustries: ["All Industries", "Retail", "Manufacturing", "Financial Services", "Healthcare"],
    applicableScenarios: ["Fire", "Structural Damage", "Utility Failure", "Chemical Spill", "Civil Unrest"],
    sections: [
      { id: "assessment", name: "Damage Assessment", description: "Rapid facility evaluation procedures" },
      { id: "relocation", name: "Relocation Procedures", description: "Alternate site activation" },
      { id: "equipment", name: "Equipment Recovery", description: "Critical equipment salvage and replacement" },
      { id: "workforce", name: "Workforce Redeployment", description: "Staff reassignment and remote work" },
      { id: "restoration", name: "Facility Restoration", description: "Repair and reconstruction planning" },
      { id: "insurance", name: "Insurance Claims", description: "Documentation and claims processing" },
    ],
    checklistItems: [
      "Identify alternate work locations",
      "Maintain equipment inventory",
      "Create critical document backup",
      "Establish employee notification system",
      "Pre-negotiate recovery site agreements",
      "Document facility with photos annually",
    ],
    rtoGuidance: "Alternate site operational: 24-48 hours, Full facility replacement: 3-12 months",
    rpoGuidance: "All critical documents and data must be backed up off-site daily",
    relatedFrameworks: ["ISO 22301", "NFPA 1600", "OSHA"],
    aiEnriched: true,
    aiTips: [
      { type: "tip", title: "Hot Site Agreements", content: "Pre-negotiate agreements with alternate facilities to enable rapid relocation during emergencies." },
      { type: "insight", title: "Virtual Capabilities", content: "Cloud-based systems significantly reduce facility dependency. Evaluate virtualization opportunities." },
      { type: "prediction", title: "Insurance Gap", content: "Standard policies often exclude certain events. Review coverage annually with a risk specialist." },
    ],
  },
  {
    code: "BCP-TELECOM-001",
    name: "Telecommunications Failure Plan",
    description: "Plan for maintaining communications and IT connectivity during telecommunications outages or service provider failures.",
    category: "IT Disaster Recovery",
    planType: "disaster_recovery",
    applicableIndustries: ["All Industries", "Financial Services", "Technology", "Contact Centers", "Healthcare"],
    applicableScenarios: ["ISP Outage", "Carrier Failure", "Cable Cut", "Network Equipment Failure", "VoIP Service Failure"],
    sections: [
      { id: "inventory", name: "Communication Inventory", description: "All communication channels and dependencies" },
      { id: "redundancy", name: "Redundancy Strategy", description: "Backup communication methods" },
      { id: "failover", name: "Failover Procedures", description: "Switching to backup systems" },
      { id: "manual", name: "Manual Fallback", description: "Operating without electronic communication" },
      { id: "testing", name: "Failover Testing", description: "Regular redundancy validation" },
    ],
    checklistItems: [
      "Identify all communication dependencies",
      "Establish backup internet providers",
      "Maintain cellular backup capabilities",
      "Document manual communication procedures",
      "Test failover monthly",
      "Maintain emergency contact lists offline",
    ],
    rtoGuidance: "Automatic failover: 0-5 minutes, Manual failover: 15-60 minutes",
    rpoGuidance: "Communication logs: Real-time replication where required for compliance",
    relatedFrameworks: ["ISO 22301", "NIST SP 800-34", "ITIL"],
    aiEnriched: true,
    aiTips: [
      { type: "tip", title: "Carrier Diversity", content: "Use multiple carriers with different physical infrastructure to avoid single-point-of-failure." },
      { type: "insight", title: "Cloud PBX Benefits", content: "Cloud-based phone systems can route calls to mobile devices automatically during office outages." },
      { type: "prediction", title: "5G Backup", content: "5G networks are becoming viable backup connections for business continuity with near-fiber speeds." },
    ],
  },
];

// BC/DR Test Templates
const bcpTestTemplatesData = [
  {
    code: "TEST-TABLETOP-001",
    name: "Tabletop Exercise - Basic",
    description: "Discussion-based exercise where team members talk through a hypothetical scenario to validate roles and procedures.",
    testType: "tabletop",
    difficulty: "beginner",
    duration: "2-4 hours",
    participantsRequired: [
      { role: "Facilitator", description: "Leads discussion and presents scenarios", required: true },
      { role: "Crisis Team Lead", description: "Primary decision maker", required: true },
      { role: "IT Representative", description: "Technical recovery expertise", required: true },
      { role: "Communications Lead", description: "Internal/external messaging", required: false },
      { role: "Business Unit Leads", description: "Departmental perspectives", required: false },
    ],
    scenarios: [
      { 
        id: "ransomware-basic",
        name: "Ransomware Attack",
        description: "Critical systems are encrypted by ransomware demanding payment",
        injects: [
          { time: "0:00", event: "IT discovers encrypted files on file server" },
          { time: "0:15", event: "Ransomware spreads to additional systems" },
          { time: "0:30", event: "Attackers demand $500,000 in cryptocurrency" },
          { time: "1:00", event: "Media outlet contacts company about the attack" },
        ],
      },
      {
        id: "power-outage",
        name: "Extended Power Outage",
        description: "Primary facility loses power for extended period",
        injects: [
          { time: "0:00", event: "Power failure at main office" },
          { time: "0:15", event: "UPS battery backup depleting" },
          { time: "0:30", event: "Generator fails to start" },
          { time: "1:00", event: "Utility estimates 24-hour restoration" },
        ],
      },
    ],
    situations: [
      { type: "during_business_hours", description: "Incident occurs during peak operations" },
      { type: "after_hours", description: "Incident occurs at 2 AM on Saturday" },
      { type: "key_person_unavailable", description: "Primary response leader is traveling internationally" },
    ],
    objectives: [
      "Validate understanding of roles and responsibilities",
      "Identify gaps in current procedures",
      "Practice decision-making under pressure",
      "Test communication protocols",
    ],
    evaluationCriteria: [
      { criterion: "Response Time", description: "Team activates within defined timeframe", weight: 20 },
      { criterion: "Role Clarity", description: "All participants understand their responsibilities", weight: 25 },
      { criterion: "Communication", description: "Information flows appropriately", weight: 25 },
      { criterion: "Decision Quality", description: "Decisions align with policy and priorities", weight: 30 },
    ],
    checklist: [
      "Schedule exercise and confirm participants",
      "Prepare scenario materials and injects",
      "Review BCP/DR plans before exercise",
      "Conduct exercise facilitation",
      "Document decisions and discussions",
      "Collect participant feedback",
      "Create findings report",
      "Schedule follow-up actions",
    ],
    aiTips: [
      { type: "tip", title: "Start Simple", content: "For first tabletop exercises, use straightforward scenarios before introducing complex multi-faceted situations." },
      { type: "insight", title: "No Wrong Answers", content: "Emphasize that the goal is learning, not testing. Create a safe environment for discussion." },
    ],
  },
  {
    code: "TEST-WALKTHROUGH-001",
    name: "Walkthrough Exercise",
    description: "Step-by-step review of BCP procedures with actual system access to validate technical accuracy.",
    testType: "walkthrough",
    difficulty: "intermediate",
    duration: "4-8 hours",
    participantsRequired: [
      { role: "Exercise Lead", description: "Coordinates walkthrough activities", required: true },
      { role: "IT Recovery Team", description: "Executes technical recovery steps", required: true },
      { role: "Business Process Owners", description: "Validates business procedures", required: true },
      { role: "Documentation Specialist", description: "Records findings and updates", required: true },
    ],
    scenarios: [
      {
        id: "dr-failover-walk",
        name: "DR Site Failover Walkthrough",
        description: "Step-by-step review of disaster recovery site activation",
        injects: [
          { time: "0:00", event: "Begin with DR plan documentation review" },
          { time: "0:30", event: "Access DR infrastructure (read-only)" },
          { time: "1:00", event: "Walk through network failover procedures" },
          { time: "2:00", event: "Review application recovery sequences" },
        ],
      },
      {
        id: "backup-restore-walk",
        name: "Backup Restoration Walkthrough",
        description: "Validate backup procedures and restoration capabilities",
        injects: [
          { time: "0:00", event: "Review backup schedules and retention" },
          { time: "0:30", event: "Verify backup integrity checks" },
          { time: "1:00", event: "Test restore of non-production data" },
          { time: "2:00", event: "Document any procedure gaps" },
        ],
      },
    ],
    situations: [
      { type: "planned_maintenance", description: "During scheduled maintenance window" },
      { type: "with_vendor_support", description: "With vendor/MSP participation" },
    ],
    objectives: [
      "Validate technical accuracy of procedures",
      "Identify outdated or missing steps",
      "Confirm system access and credentials work",
      "Update documentation based on findings",
    ],
    evaluationCriteria: [
      { criterion: "Procedure Accuracy", description: "Steps match actual system requirements", weight: 35 },
      { criterion: "Completeness", description: "No missing steps identified", weight: 25 },
      { criterion: "Access Verification", description: "All required access available", weight: 20 },
      { criterion: "Documentation Quality", description: "Clear and understandable procedures", weight: 20 },
    ],
    checklist: [
      "Gather current BCP/DR documentation",
      "Ensure non-production test environment",
      "Verify participant access rights",
      "Execute step-by-step procedure review",
      "Test actual system access (read-only)",
      "Document gaps and inaccuracies",
      "Update procedures immediately",
      "Create improvement action items",
    ],
    aiTips: [
      { type: "tip", title: "Use Non-Production", content: "Always use non-production environments for walkthroughs to avoid impacting live systems." },
      { type: "insight", title: "Fresh Eyes Benefit", content: "Include someone unfamiliar with the systems - they'll spot assumptions and missing steps." },
    ],
  },
  {
    code: "TEST-SIMULATION-001",
    name: "Simulation Exercise",
    description: "Realistic exercise that simulates actual disaster conditions with limited advance warning to test response capabilities.",
    testType: "simulation",
    difficulty: "advanced",
    duration: "1-2 days",
    participantsRequired: [
      { role: "Exercise Director", description: "Overall exercise management", required: true },
      { role: "Control Team", description: "Manages scenario progression", required: true },
      { role: "All DR Team Members", description: "Respond as they would in real incident", required: true },
      { role: "Observers/Evaluators", description: "Document actions and timing", required: true },
      { role: "Safety Officer", description: "Ensures exercise safety", required: true },
    ],
    scenarios: [
      {
        id: "full-dr-simulation",
        name: "Full DR Site Activation",
        description: "Simulate primary site loss and activate disaster recovery",
        injects: [
          { time: "0:00", event: "Notification: Primary data center is inaccessible" },
          { time: "0:30", event: "DR team assembles (virtually or physically)" },
          { time: "1:00", event: "Begin DR site activation procedures" },
          { time: "4:00", event: "Critical applications should be operational" },
          { time: "8:00", event: "All tier-1 applications restored" },
          { time: "24:00", event: "Full business operations at DR site" },
        ],
      },
      {
        id: "cyber-incident-sim",
        name: "Cyber Incident Response",
        description: "Simulate major cybersecurity breach requiring coordinated response",
        injects: [
          { time: "0:00", event: "Security alert: Unusual data exfiltration detected" },
          { time: "0:30", event: "Scope expanding - multiple systems compromised" },
          { time: "1:00", event: "Decision required: Isolate systems or continue monitoring" },
          { time: "2:00", event: "Regulatory notification deadline approaching" },
          { time: "4:00", event: "Media inquiry about potential breach" },
        ],
      },
    ],
    situations: [
      { type: "surprise_initiation", description: "Exercise initiated without advance warning" },
      { type: "remote_participation", description: "Team members participate from multiple locations" },
      { type: "vendor_dependencies", description: "Exercise includes vendor/partner coordination" },
    ],
    objectives: [
      "Validate end-to-end recovery capabilities",
      "Measure actual recovery times",
      "Test team coordination under pressure",
      "Identify process and technology gaps",
    ],
    evaluationCriteria: [
      { criterion: "RTO Achievement", description: "Systems recovered within target RTO", weight: 30 },
      { criterion: "RPO Achievement", description: "Data loss within acceptable RPO", weight: 25 },
      { criterion: "Team Coordination", description: "Effective communication and handoffs", weight: 25 },
      { criterion: "Problem Resolution", description: "Ability to handle unexpected issues", weight: 20 },
    ],
    checklist: [
      "Obtain executive sponsorship",
      "Plan scenario and inject timeline",
      "Prepare observer guidelines",
      "Notify stakeholders of exercise",
      "Execute simulation",
      "Track all actions and decisions",
      "Conduct hot wash immediately after",
      "Develop comprehensive findings report",
      "Create remediation action plan",
      "Schedule follow-up exercises",
    ],
    aiTips: [
      { type: "tip", title: "Safety First", content: "Establish clear safety boundaries and 'exercise halt' procedures before starting." },
      { type: "insight", title: "Realistic Pressure", content: "Add realistic time pressure through injects to test decision-making under stress." },
      { type: "prediction", title: "Expect Surprises", content: "Real disasters always include unexpected challenges. Inject unforeseen complications to test adaptability." },
    ],
  },
  {
    code: "TEST-FULL-001",
    name: "Full Interruption Test",
    description: "Complete failover to backup systems with actual processing, providing the most realistic validation of recovery capabilities.",
    testType: "full_interruption",
    difficulty: "advanced",
    duration: "1-3 days",
    participantsRequired: [
      { role: "Executive Sponsor", description: "Authorizes production impact", required: true },
      { role: "Test Director", description: "Overall test management", required: true },
      { role: "Technical Lead", description: "Manages technical execution", required: true },
      { role: "All Recovery Teams", description: "Execute recovery procedures", required: true },
      { role: "Business Validation Team", description: "Verify business functionality", required: true },
      { role: "Rollback Team", description: "Ready to restore if needed", required: true },
    ],
    scenarios: [
      {
        id: "full-failover",
        name: "Complete DR Failover",
        description: "Full production failover to DR site with real transaction processing",
        injects: [
          { time: "-24:00", event: "Final go/no-go decision" },
          { time: "0:00", event: "Initiate production shutdown (planned)" },
          { time: "0:30", event: "Confirm clean shutdown of production" },
          { time: "1:00", event: "Begin DR activation" },
          { time: "4:00", event: "DR site operational - begin testing" },
          { time: "8:00", event: "Full business validation complete" },
          { time: "+24:00", event: "Plan and execute failback" },
        ],
      },
    ],
    situations: [
      { type: "planned_weekend", description: "Executed during planned maintenance window" },
      { type: "customer_notification", description: "Customers notified in advance" },
    ],
    objectives: [
      "Prove recovery capabilities work in production",
      "Validate actual RTO/RPO achievements",
      "Test full business transaction processing",
      "Verify failback procedures",
    ],
    evaluationCriteria: [
      { criterion: "Recovery Success", description: "All critical systems recovered successfully", weight: 35 },
      { criterion: "Data Integrity", description: "No data loss or corruption", weight: 30 },
      { criterion: "Transaction Processing", description: "Real transactions processed correctly", weight: 20 },
      { criterion: "Failback Success", description: "Clean return to production", weight: 15 },
    ],
    checklist: [
      "Obtain executive and board approval",
      "Complete all prerequisite tests",
      "Notify customers and partners",
      "Prepare detailed test script",
      "Stage rollback procedures",
      "Execute production shutdown",
      "Activate DR environment",
      "Validate all applications",
      "Process test transactions",
      "Document results and timing",
      "Execute failback",
      "Verify production restoration",
      "Create comprehensive report",
    ],
    aiTips: [
      { type: "tip", title: "Prerequisite Testing", content: "Complete tabletop, walkthrough, and simulation exercises before attempting full interruption tests." },
      { type: "insight", title: "Business Approval", content: "Full interruption tests require explicit business approval due to potential customer impact." },
      { type: "prediction", title: "First-Time Challenges", content: "First full tests typically encounter issues. Plan extra time and have rollback procedures ready." },
    ],
  },
  {
    code: "TEST-TABLETOP-EXEC",
    name: "Executive Crisis Tabletop",
    description: "Executive-level tabletop exercise focused on strategic decision-making and crisis communication during major incidents.",
    testType: "tabletop",
    difficulty: "intermediate",
    duration: "2-3 hours",
    participantsRequired: [
      { role: "CEO/Managing Director", description: "Ultimate decision authority", required: true },
      { role: "CFO", description: "Financial impact assessment", required: true },
      { role: "CIO/CTO", description: "Technology recovery decisions", required: true },
      { role: "CISO", description: "Security incident expertise", required: false },
      { role: "Legal Counsel", description: "Regulatory and legal implications", required: true },
      { role: "Communications/PR", description: "External messaging", required: true },
    ],
    scenarios: [
      {
        id: "breach-executive",
        name: "Major Data Breach",
        description: "Customer data breach requiring regulatory notification and public disclosure",
        injects: [
          { time: "0:00", event: "CISO reports: 10 million customer records may be compromised" },
          { time: "0:20", event: "Initial investigation suggests 6-month exposure window" },
          { time: "0:40", event: "Legal advises 72-hour regulatory notification required" },
          { time: "1:00", event: "Social media posts appear about the breach" },
          { time: "1:20", event: "Major customer threatens contract termination" },
        ],
      },
      {
        id: "ransomware-executive",
        name: "Ransomware Crisis",
        description: "Ransomware attack disrupting critical operations with ransom demand",
        injects: [
          { time: "0:00", event: "IT reports: All production systems encrypted by ransomware" },
          { time: "0:15", event: "Ransom demand: $5 million in cryptocurrency, 48-hour deadline" },
          { time: "0:30", event: "Recovery estimate without paying: 2-3 weeks" },
          { time: "0:45", event: "Attackers threaten to publish stolen data" },
          { time: "1:00", event: "FBI contacts company about the attack" },
        ],
      },
    ],
    situations: [
      { type: "board_meeting_day", description: "Crisis occurs during board meeting" },
      { type: "earnings_announcement", description: "Incident occurs day before earnings release" },
    ],
    objectives: [
      "Practice executive decision-making under pressure",
      "Test crisis communication protocols",
      "Validate regulatory notification procedures",
      "Assess reputational risk management",
    ],
    evaluationCriteria: [
      { criterion: "Decision Speed", description: "Timely decisions on critical issues", weight: 25 },
      { criterion: "Communication Quality", description: "Clear, consistent messaging", weight: 30 },
      { criterion: "Stakeholder Management", description: "Appropriate stakeholder engagement", weight: 25 },
      { criterion: "Risk Consideration", description: "Balanced assessment of options", weight: 20 },
    ],
    checklist: [
      "Confirm executive availability",
      "Prepare executive briefing materials",
      "Create realistic scenario for industry",
      "Prepare media simulation (mock interviews)",
      "Conduct exercise",
      "Debrief with executives immediately",
      "Document key decisions and rationale",
      "Create action items for gaps",
    ],
    aiTips: [
      { type: "tip", title: "Respect Time", content: "Executive exercises should be focused and time-bound. Prepare materials thoroughly to maximize learning." },
      { type: "insight", title: "Real Stakes", content: "Include realistic financial and reputational consequences to engage executive attention." },
    ],
  },
];

export async function seedBCPCatalog() {
  console.log("Seeding BC/DR Plan Catalog...");
  
  // Seed BCP Plan Catalog
  for (const plan of bcpPlanCatalogData) {
    try {
      await db.insert(bcpPlanCatalog).values(plan).onConflictDoNothing();
    } catch (error) {
      console.log(`Plan ${plan.code} may already exist, skipping...`);
    }
  }
  
  console.log(`Seeded ${bcpPlanCatalogData.length} BC/DR plan templates`);
  
  // Seed BCP Test Templates
  for (const template of bcpTestTemplatesData) {
    try {
      await db.insert(bcpTestTemplates).values(template).onConflictDoNothing();
    } catch (error) {
      console.log(`Test template ${template.code} may already exist, skipping...`);
    }
  }
  
  console.log(`Seeded ${bcpTestTemplatesData.length} BC/DR test templates`);
  
  console.log("BC/DR Catalog seeding complete!");
}
